// Generated by oort app codegen. Do not edit.

export interface OortQueries {
  "ops-summary": { parameters: { "days": number; }; rows: unknown[][] };
  "priority-backlog": { parameters: { "days": number; "limit": number; "queue": string; }; rows: unknown[][] };
  "team-health": { parameters: { "days": number; }; rows: unknown[][] };
  "ticket-volume": { parameters: { "days": number; }; rows: unknown[][] };
}

export type OortQueryName = keyof OortQueries;
